name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         os: [ubuntu-18.04]

    steps:
    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install -y mtools liblzma-dev binutils
         run: |
         sudo apt-get update
         
    - uses: actions/checkout@v2
    - name: Compile EFI x86_64
      run: |
        git fetch --unshallow --tags
        make --trace bin-x86_64-efi/ipxe.efi
      working-directory: ./src

      

