name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         os: [ubuntu-18.04]

    steps:
    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install -y mtools liblzma-dev binutils
         run: |
         sudo apt-get update
         gcc --version
         uname -a
         
    - uses: actions/checkout@v2
    - name: Compile EFI x86_64 up to blib
      run: |
        git fetch --unshallow --tags
        git tag --list
        make bin-x86_64-efi/blib.a
        git describe --tags --always --long --abbrev=1 --match "v*"
        git describe --tags --always --long --abbrev=1 --match "v*" master
      working-directory: ./src
      
    - name: Compile EFI x86_64 with --trace
      run: make --trace bin-x86_64-efi/ipxe.efi
      working-directory: ./src

      

